name: pytorch_env
channels:
  - pytorch
  - anaconda
  - conda-forge
dependencies:
  - anyio=3.3.0=py39h2804cbe_0
  - appnope=0.1.2=py39h2804cbe_1
  - argon2-cffi=20.1.0=py39h5161555_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - beautifulsoup4=4.10.0=pyha770c72_0
  - bleach=4.1.0=pyhd8ed1ab_0
  - bokeh=2.3.3=py39h2804cbe_0
  - brotlipy=0.7.0=py39h5161555_1001
  - bs4=4.10.0=hd8ed1ab_0
  - ca-certificates=2021.5.30=h4653dfc_0
  - catalogue=2.0.6=py39h2804cbe_0
  - certifi=2021.5.30=py39h2804cbe_0
  - cffi=1.14.6=py39h52b1de0_1
  - chardet=4.0.0=py39h2804cbe_1
  - charset-normalizer=2.0.0=pyhd8ed1ab_0
  - click=7.1.2=pyh9f0ad1d_0
  - cloudpickle=2.0.0=pyhd8ed1ab_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.7=py39h73257c9_0
  - cymem=2.0.5=py39hfb83b0d_2
  - cython-blis=0.7.4=py39h038c1d3_0
  - cytoolz=0.11.0=py39h5161555_3
  - dask=2021.9.0=pyhd8ed1ab_0
  - dask-core=2021.9.0=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - debugpy=1.4.1=py39hfb83b0d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - distributed=2021.9.0=py39h2804cbe_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - filelock=3.0.12=pyh9f0ad1d_0
  - freetype=2.10.4=h17b34a0_1
  - fsspec=2021.8.1=pyhd8ed1ab_0
  - future=0.18.2=py39h2804cbe_3
  - heapdict=1.0.1=py_0
  - huggingface_hub=0.0.17=pyhd8ed1ab_0
  - idna=3.1=pyhd3deb0d_0
  - importlib-metadata=4.8.1=py39h2804cbe_0
  - importlib_metadata=4.8.1=hd8ed1ab_0
  - ipykernel=6.4.1=py39h32adebf_0
  - ipython=7.27.0=py39h32adebf_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jbig=2.1=h3422bc3_2003
  - jedi=0.18.0=py39h2804cbe_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h27ca646_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=7.0.2=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39h2804cbe_0
  - jupyter_server=1.11.0=pyhd8ed1ab_0
  - jupyterlab=3.1.12=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.8.1=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - lcms2=2.12=had6a04f_0
  - lerc=2.2.1=h9f76cd9_0
  - libblas=3.9.0=11_osxarm64_openblas
  - libcblas=3.9.0=11_osxarm64_openblas
  - libcxx=12.0.1=h168391b_0
  - libdeflate=1.7=h27ca646_5
  - libffi=3.4.2=hbdafb3b_1
  - libgfortran=5.0.0.dev0=11_0_1_hf114ba7_23
  - libgfortran5=11.0.1.dev0=hf114ba7_23
  - liblapack=3.9.0=11_osxarm64_openblas
  - libopenblas=0.3.17=openmp_h5dd58f0_1
  - libpng=1.6.37=hf7e6567_2
  - libprotobuf=3.16.0=hccf11d3_0
  - libsodium=1.0.18=h27ca646_1
  - libtiff=4.3.0=hc6122e1_1
  - libwebp-base=1.2.1=h3422bc3_0
  - llvm-openmp=12.0.1=hf3c4609_1
  - locket=0.2.0=py_2
  - lz4-c=1.9.3=hbdafb3b_1
  - markupsafe=2.0.1=py39h5161555_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - memory_profiler=0.58.0=py_0
  - mistune=0.8.4=py39h5161555_1004
  - msgpack-python=1.0.2=py39h4d2d688_1
  - murmurhash=1.0.5=py39hfb83b0d_0
  - nbclassic=0.3.1=pyhd8ed1ab_1
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbconvert=6.1.0=py39h2804cbe_1
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h9aa5885_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - ninja=1.10.2=h4d860bb_0
  - nltk=3.6.3=pyhd8ed1ab_0
  - notebook=6.4.3=pyha770c72_0
  - numpy=1.21.2=py39h1f3b974_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h062765e_1
  - openssl=1.1.1l=h3422bc3_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.3=py39h7f752ed_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - partd=1.2.0=pyhd8ed1ab_0
  - pathy=0.6.0=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.2=py39ha74c66e_0
  - pip=21.2.4=pyhd8ed1ab_0
  - preshed=3.0.5=py39hfb83b0d_1
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - psutil=5.8.0=py39h5161555_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pydantic=1.8.2=py39h5161555_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py39h5161555_2
  - pysocks=1.7.1=py39h2804cbe_3
  - python=3.9.7=h54d631c_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.0=cpu_py39he8fdc14_2
  - pytz=2021.1=pyhd8ed1ab_0
  - pyyaml=5.4.1=py39h5161555_1
  - pyzmq=22.2.1=py39h02c6a76_0
  - readline=8.1=hedafd6a_0
  - regex=2021.8.28=py39h5161555_0
  - requests=2.26.0=pyhd8ed1ab_0
  - requests-unixsocket=0.2.0=py_0
  - sacremoses=0.0.43=pyh9f0ad1d_0
  - scipy=1.7.0=py39h5060c3b_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py39h2804cbe_0
  - shellingham=1.4.0=pyh44b312d_0
  - six=1.16.0=pyh6c4a22f_0
  - sleef=3.5.1=h27ca646_1
  - smart_open=5.2.1=pyhd8ed1ab_0
  - sniffio=1.2.0=py39h2804cbe_1
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - soupsieve=2.0.1=py_1
  - spacy=3.1.2=py39h776e71f_0
  - spacy-legacy=3.0.8=pyhd8ed1ab_0
  - spacy-model-en_core_web_sm=3.1.0=pyhd8ed1ab_0
  - sqlite=3.36.0=h72a2b83_1
  - srsly=2.4.1=py39hfb83b0d_0
  - tblib=1.7.0=pyhd8ed1ab_0
  - terminado=0.12.1=py39h2804cbe_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - thinc=8.0.10=py39h776e71f_0
  - tk=8.6.11=he1e0b03_1
  - tokenizers=0.10.3=py39hab32027_1
  - toolz=0.11.1=py_0
  - torchtext=0.6.0=py_1
  - torchvision=0.2.2=py_3
  - tornado=6.1=py39h5161555_1
  - tqdm=4.62.2=pyhd8ed1ab_0
  - traitlets=5.1.0=pyhd8ed1ab_0
  - transformers=4.10.2=pyhd8ed1ab_0
  - typer=0.3.2=pyhd8ed1ab_0
  - typing-extensions=3.10.0.0=hd8ed1ab_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - tzdata=2021a=he74cb21_1
  - urllib3=1.26.6=pyhd8ed1ab_0
  - wasabi=0.8.2=pyh44b312d_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py39h2804cbe_4
  - wheel=0.37.0=pyhd8ed1ab_1
  - widgetsnbextension=3.5.1=py39h2804cbe_4
  - xz=5.2.5=h642e427_1
  - yaml=0.2.5=h642e427_0
  - zeromq=4.3.4=hbdafb3b_1
  - zict=2.0.0=py_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h31e879b_1009
  - zstd=1.5.0=h861e0a7_0
  - pip:
    - anyascii==0.3.0
    - contractions==0.0.52
    - gensim==4.1.2
    - pyahocorasick==1.4.2
    - revtok==0.0.3
    - textsearch==0.0.21
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/pytorch_env
